# [START runtime]
runtime: python27
api_version: 1
threadsafe: yes
# [END runtime]
handlers:
- url: /(.+)
  static_files: out/\1
  upload: out/(.*)
- url: /
  static_files: out/index.html
  upload: out/index.html
skip_files:
- ^(?!out)  # Skip any files not in the dist folder