# [START runtime]
runtime: python27
api_version: 1
threadsafe: yes
handlers:
- url: /dist/_next/static
  static_files: dist/
  upload: dist/(.*)
- url: /
  static_files: dist/index.html
  upload: dist/index.html